config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
  devise_for :users
  root to: 'pages#introduction'
  get 'about', to: 'pages#about'
  post 'send_provider', to: 'pages#send_provider'
  get 'home', to: 'pages#home'
  get 'pending_providers', to: 'pages#pending_providers'
  resources :providers, only: [ :index, :show, :new, :create, :update ] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [ :index, :update ] do
    resources :payments, only: [ :new ]
    resources :reviews, only: [ :new, :create ]
  end
  get 'services/:id/available_time_slots', to: 'services#available_time_slots'
  post 'prepare_payment', to: 'bookings#prepare_payment'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get '*unmatched_route', to: 'application#raise_not_found'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, foreign_key: "user_id", class_name: "User"
  belongs_to :service
  has_one :review, dependent: :destroy

  before_validation :set_end_datetime, if: :new_record?
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  validates :status, presence: true

  private

  def set_end_datetime
    self.end_datetime = self.start_datetime + service.min_duration
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: :update
  before_action :change_status, only: :index

  def create
    @booking = Booking.new(bookings_params)
    @provider = Provider.find(params[:provider_id])
    @service = Service.find(params["booking"]["service_id"])
    @booking.customer = current_user
    @booking.status = "accepted"
    @booking.payment_status = "pending"
    @booking.service = @service
    if @booking.save!
      UserMailer.thankyou(@booking.customer, @booking, @provider).deliver_later
      redirect_to bookings_path
    else
      @markers = [{
        lat: @provider.latitude,
        lng: @provider.longitude,
        infoWindow: render_to_string(partial: "providers/info_window", locals: { provider: @provider })
      }]
      @reviews = []
      @provider.bookings.each do |booking|
        if  booking.review != nil
          @reviews << booking.review
        end
      end
      @url = params[:url]
      redirect_to provider_path(@provider)
    end
  end

  def index
    @bookings = Booking.where(customer: current_user)

    @accepted = @bookings.where(status: "accepted")
    @completed = @bookings.where(status: "completed")
    @canceled = @bookings.where(status: "canceled")
  end

  def update
    set_booking
    @booking.update(bookings_params)
    @booking.status == "canceled"
    @provider = @booking.service.provider
    UserMailer.cancel(@booking.customer, @booking, @provider).deliver_later
    redirect_to bookings_path
  end



  private

  def change_status
    @bookings = Booking.where(status: "accepted")
    @bookings.each do |booking|
      if booking.start_datetime - Time.zone.now < 0
        booking.status = "completed"
        booking.save
      end
    end
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def bookings_params
    params.require(:booking).permit(:start_datetime, :end_datetime, :status)
  end
end

app/views/bookings/index.html.erb
<%= render 'shared/container' %>
<div class="container">

  <strong><h1 id="title" class="pt-2">Mis turnos</h1></strong>
  <div class="align-left">
    <ul class="nav nav-pills my-3" style="justify-content: center;" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button id="filters" class="btn btn-filters m-1 toggle-filters toggle-filters-active " id="pills-home-tab" data-toggle="pill" data-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true" data-toggle-class="is-selected">Pendientes</button>
      </li>
      <li class="nav-item" role="presentation">
        <button id="filters" class="btn btn-filters m-1 toggle-filters" id="pills-profile-tab" data-toggle="pill" data-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false" data-toggle-class>Finalizados</button>
      </li>
      <li class="nav-item" role="presentation">
        <button id="filters" class="btn btn-filters m-1 toggle-filters" id="pills-contact-tab" data-toggle="pill" data-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false" data-toggle-class>Cancelados</button>
      </li>
    </ul>
  </div>
  <div class="tab-content mt-5" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="cards">
        <div class="row">
          <% @accepted.each do |booking| %>
            <div class="col-12 col-md-4 mb-2">
                <div class="card-product">
                  <%= cl_image_tag booking.service.provider.photos.first.key, class: "card-img-index-pending" %>
                  <div class="card-product-infos mt-2 mr-2">
                    <h2><%= booking.service.provider.name %></h2>
                    <p class="description" style="margin-top:0"><%= booking.service.title %></p>
                    <p class="description" style="margin-top:0">Precio: <strong>$ <%= booking.service.price %></strong></p>
                    <p class="description" style="margin:0">Fecha del turno: <%= booking.start_datetime.strftime('%d/%m/%Y') %>, <%= booking.start_datetime.strftime('%H:%M') %>hs</p>
                    <% if booking.payment_status == "paid" %>
                      <span class="badge badge-success" style="color:white;font-size:12px;border-radius:5px">Pago Confirmado</span>
                    <% end %>
                    <div class="">
                      <% if booking.payment_status == "pending" %>
                        <%= link_to "Pagar", new_booking_payment_path(booking), class: "btn btn-primary w-100 mt-1 mb-2", style:"font-size:12px;border-radius:5px;height:30px" %>
                      <% end %>
                      <%= simple_form_for booking do |f| %>
                        <%= f.hidden_field :status, value: "canceled" %>
                        <%=f.submit "Cancelar", class: "btn btn-light w-100 my-0 py-1", style: "color: #343A40;font-size:12px", data: { confirm: "Cancelar turno?" } %>
                      <% end %>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">

      <div class="cards">
        <div class="row">
          <% @completed.each do |booking| %>
            <div class="col-12 col-md-4 mb-2">
                <div class="card-product">
                  <%= cl_image_tag booking.service.provider.photos.first.key, class: "card-img-index-pending" %>
                  <div class="card-product-infos mt-2 mr-2">
                    <h2><%= booking.service.provider.name %></h2>
                    <p class="description" style="margin:0"><%= booking.service.title %></p>
                    <p class="description" style="margin-top:0">Precio: <strong>$ <%= booking.service.price %></strong></p>
                    <p class="description" style="margin:0">Fecha del turno: <%= booking.start_datetime.strftime('%d/%m/%Y') %>, <%= booking.start_datetime.strftime('%H:%M') %>hs</p>
                    <% if booking.review.blank? %>
                      <%= link_to 'Opinar', new_booking_review_path(booking), class: "btn btn-primary w-100 mt-1 mb-2", style:"font-size:12px;border-radius:5px;height:30px" %>
                    <% else %>
                      <button type="button" class="btn btn-primary w-100 mt-1 mb-2", style="font-size:12px;border-radius:5px;height:30px" data-toggle="modal" data-target="#exampleModal"> Ver opinión</button>
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Tu opinión</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <%= booking.review.content %>
                              <% booking.review.rating.times do %>
                                <i class="fas fa-star"></i>
                              <% end %>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <div class="cards pb" style="padding-bottom: 80px">
        <div class="row">
          <% @canceled.each do |booking| %>
            <div class="col-12 col-md-4 mb-2">
                <div class="card-product mt-2 mr-2">
                  <%= cl_image_tag booking.service.provider.photos.first.key, class: "card-img-index-pending" %>
                  <div class="card-product-infos">
                    <h2><%= booking.service.provider.name %></h2>
                    <p class="description" style="margin:0"><%= booking.service.title %></p>
                    <p class="description" style="margin-top:0">Precio: <strong>$ <%= booking.service.price %></strong></p>
                    <p class="description" style="margin:0">Fecha del turno: <%= booking.start_datetime.strftime('%d/%m/%Y') %>, <%= booking.start_datetime.strftime('%H:%M') %>hs</p>
                    <p style="color: red; font-weight: bold">Cancelado</p>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container" style="height:15px">
</div>