config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
  devise_for :users
  root to: 'pages#introduction'
  get 'about', to: 'pages#about'
  post 'send_provider', to: 'pages#send_provider'
  get 'home', to: 'pages#home'
  get 'pending_providers', to: 'pages#pending_providers'
  resources :providers, only: [ :index, :show, :new, :create, :update ] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [ :index, :update ] do
    resources :payments, only: [ :new ]
    resources :reviews, only: [ :new, :create ]
  end
  get 'services/:id/available_time_slots', to: 'services#available_time_slots'
  post 'prepare_payment', to: 'bookings#prepare_payment'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get '*unmatched_route', to: 'application#raise_not_found'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
end

app/views/shared/_bottom_navbar.html.erb
<nav id="bottom-navbar" class="navbar fixed-bottom navbar-light bg-light">
  <div class="d-flex justify-content-between w-100">
    <%= link_to home_path do  %>
      <div class="icons d-flex flex-column">
        <i class="fas fa-home"></i>Home
      </div>
    <% end %>

    <% if current_user&.admin? %>
      <%= link_to pending_providers_path do %>
        <div class="icons d-flex flex-column align-center">
          <i class="fas fa-store"></i>Proveedores
        </div>
      <% end %>
    <% elsif user_signed_in? %>
      <%= link_to bookings_path do  %>
        <div class="icons d-flex flex-column align-center">
          <i class="far fa-calendar-check"></i>Mis Turnos
        </div>
      <% end %>
    <% else %>
      <%= link_to new_user_registration_path do  %>
        <div class="icons d-flex flex-column align-center">
          <i class="far fa-calendar-check"></i>Registrate
        </div>
      <% end %>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path(current_user) do  %>
        <div class="icons d-flex flex-column align-center">
          <i class="fas fa-user"></i>Mi Perfil
        </div>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do  %>
        <div class="icons d-flex flex-column align-center">
          <i class="fas fa-user"></i>Ingresá
        </div>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_cards_home.html.erb
<div class="row justify-content-center">
  <% @providers.each do |provider| %>
    <div class="col-12 col-md-6 col-lg-3 mt-3">
      <%= link_to provider_path(provider) do  %>
          <div class="card h-100">
            <%= cl_image_tag provider.photos.first.key, class: "desktop-img mb-1" %>
            <div class="card-body bg-light">
              <h5 class="card-title mb-1"> <strong><%= provider.name %></h5></strong>
              <% provider.rating.times do %>
                <i class="fas fa-star my-2" style="font-size: 10px"></i>
              <% end %>
              <p class="text-dark fs-6 fw-bolder mb-0"><%= provider.category %></span></p>
              <p style="font-size: 12px" class="text-dark  my-1"><%= provider.neighborhood.partition(",").first %></p>
              <p style="font-size: 12px" class="text-dark font-italic"><%= provider.address.partition(",").first %></p>
              <div class= "d-flex justify-content-between">
                <p class="distance m-0" data-latitude="<%= provider.latitude%>" data-longitude="<%= provider.longitude%>"></p>
                <i class="fas fa-location-arrow"></i>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide hidden-md hidden-sm col-xs-12" data-ride="carousel">
  <div class="carousel-inner">
    <% @providers.each_with_index do |provider, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : "" %>">
        <%= link_to provider_path(provider) do  %>
          <div class="col-12 col-md-4 col-lg-3 mt-3">
            <div class="card rounded-3 h-100">
              <%= cl_image_tag provider.photos.first.key, class: "carousel-img" %>
              <div class="card-body bg-light">
                <h5 class="card-title mb-1"> <strong><%= provider.name %></h5></strong>
                <% provider.rating.times do %>
                  <i class="fas fa-star my-2" style="font-size: 10px"></i>
                <% end %>
                <p class="text-dark fs-6 fw-bolder mb-0"><%= provider.category %></span></p>
                <p style="font-size: 12px" class="text-dark  my-0"><%= provider.neighborhood.partition(",").first %></p>
                <p style="font-size: 12px" class="text-dark font-italic"><%= provider.address.partition(",").first %></p>
                <div class= "d-flex">
                  <p class="distance m-0 pr-4" data-latitude="<%= provider.latitude%>" data-longitude="<%= provider.longitude%>"></p>
                  <i class="fas fa-location-arrow"></i>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_container.html.erb
<div class="container" style="height:75px">
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="top-navbar" class="navbar fixed-top navbar-light bg-light">
  <div class="d-flex justify-content-between w-100">
    <%= link_to root_path do %>
      <img src="https://res.cloudinary.com/divzp8hs4/image/upload/v1613239833/Turna/Logo_Turna_Full_tgoyaw.png" alt="Turna Logo" style="height:30px">
    <% end %>
    <div class="navbar-registriation d-flex">
      <% if user_signed_in? %>
        <div class="navbar-avatar m-0 pr-0">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, style:"height:40px;width:40px", class:"rounded-circle ml-2" %>
          <% else %>
            <%= image_tag 'https://res.cloudinary.com/dmtio0viw/image/upload/v1613240448/Turna/My_profile-orange-300x300_v5b2u3.png' , style:"height:40px;width:40px", class:"rounded-circle mr-5" %>
          <% end %>
        </div>
        <strong><span><%= link_to "Cerrar Sesion", destroy_user_session_path, :method => :delete, class: "nav-link mr-0", style:"color: black" %></span></strong>
      <% else %>
        <div class="d-flex m-0 pr-0 pl-4">
          <strong><%= link_to "Registrate", new_user_registration_path, class: "nav-link", style:"color: black" %></strong>
          <strong><%= link_to "Ingresar", new_user_session_path, class: "nav-link mr-1", style:"color: black" %></strong>
        </div>
      <% end %>
    </div>
  </div>
</nav>



<nav id="bottom-navbar" class="navbar fixed-bottom navbar-light bg-light">
  <div class="d-flex justify-content-between w-100">
    <%= link_to root_path do  %>
      <div class="icons d-flex flex-column">
        <i class="fas fa-home"></i>Home
      </div>
    <% end %>
    <%= link_to bookings_path do  %>
      <div class="icons d-flex flex-column align-center">
        <i class="far fa-calendar-check"></i>Mis Turnos
      </div>
    <% end %>


    <% if  %>
      <%= link_to edit_user_registration_path(current_user) do  %>
        <div class="icons d-flex flex-column align-center">
          <i class="fas fa-user"></i>Mi Perfil
        </div>
      <% end %>
    <% else %>
        <div class="icons d-flex flex-column align-center">
          <i class="fas fa-user fa-disabled"></i>Mi Perfil
        </div>
    <% end %>
  </div>
</nav>

app/views/shared/_navbars.html.erb
<% if controller_name == "providers" && (action_name == "show" || action_name == "index") %>
  <%= render 'shared/search_top' %>
  <%= render 'shared/bottom_navbar' %>
<% elsif controller_name == "pages" && action_name == "introduction" %>
<% elsif controller_name == "pages" && action_name == "home" && current_user != nil %>
  <%= render 'shared/regular_top' %>
  <%= render 'shared/bottom_navbar' %>
<% elsif controller_name == "pages" && action_name == "home" %>
  <%= render 'shared/regular_top' %>
<% elsif controller_name == "sessions" && action_name == "new"  %>
  <%= render 'shared/regular_top' %>
<% elsif controller_name == "registrations" && action_name == "new"  %>
  <%= render 'shared/regular_top' %>
<% else %>
  <%= render 'shared/regular_top' %>
  <%= render 'shared/bottom_navbar' %>
<% end %>

app/views/shared/_regular_top.html.erb
<nav id="top-navbar" class="navbar fixed-top navbar-light bg-light">
  <div class="d-flex justify-content-between w-100">
    <%= link_to home_path do %>
      <img src="https://res.cloudinary.com/divzp8hs4/image/upload/v1615419298/Turna/Logo_TurnaOK.png" alt="Turna Logo" style="height:30px">
    <% end %>
    <div class="navbar-registriation d-flex">
      <% if user_signed_in? %>
        <div class="navbar-avatar m-0 pr-0">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, style:"height:40px;width:40px", class:"rounded-circle ml-2" %>
          <% else %>
            <%= image_tag 'https://res.cloudinary.com/dmtio0viw/image/upload/v1613240448/Turna/My_profile-orange-300x300_v5b2u3.png' , style:"height:40px;width:40px", class:"rounded-circle" %>
          <% end %>
        </div>
        <strong><span><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete, class: "nav-link mr-0", style:"color: black" %></span></strong>
      <% else %>
        <div class="d-flex m-0 pr-0 pl-4">
          <strong><%= link_to "Registrate", new_user_registration_path, class: "nav-link", style:"color: black" %></strong>
          <strong><%= link_to "Ingresá", new_user_session_path, class: "nav-link mr-1", style:"color: black" %></strong>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_search_top.html.erb
<nav id="search-navbar" class="navbar fixed-top navbar-light bg-light m-0 d-flex">
  <div class="bg-light p-0">
    <div id="search-form">
      <%= form_with local: true, url: providers_path, method: :get do |f| %>
        <div class="row align-items-center m-0 d-flex">
          <div class="mb-2 ml-0 col-7 col-sm-12 col-md-6 p-0">
            <%=f.text_field :localidad, as: :string, required: true, placeholder:"Ubicación", id: "provider_address", style: "font-size: 15px" %>
          </div>
          <div class="mb-2 col-3 col-sm-12 col-md-6 p-0">
            <%= f.select :categoria, [["Barberia", "Barberia"], ["Veterinaria", "Veterinaria"]], required: true, prompt: 'Servicio', style: "font-size: 12px!important;" %>
          </div>
          <div class="mb-2 col-2 col-md-2">
            <%= f.button class: "btn btn-primary rounded-circle", style: "width:40px;height:40px;", type: 'submit' do %>
              <i class='fas fa-search' ></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>