config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
  devise_for :users
  root to: 'pages#introduction'
  get 'about', to: 'pages#about'
  post 'send_provider', to: 'pages#send_provider'
  get 'home', to: 'pages#home'
  get 'pending_providers', to: 'pages#pending_providers'
  resources :providers, only: [ :index, :show, :new, :create, :update ] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [ :index, :update ] do
    resources :payments, only: [ :new ]
    resources :reviews, only: [ :new, :create ]
  end
  get 'services/:id/available_time_slots', to: 'services#available_time_slots'
  post 'prepare_payment', to: 'bookings#prepare_payment'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get '*unmatched_route', to: 'application#raise_not_found'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
end

app/views/pages/about.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <strong><h1 id="title" class="m-3">¿Quiénes somos?</h1></strong>

      <div class="integrante" style="display: flex;">
        <div class="img">
          <img src="https://media-exp1.licdn.com/dms/image/C4D03AQF2zYMe2o2Dlg/profile-displayphoto-shrink_800_800/0/1608524544490?e=1619049600&v=beta&t=5_Y75aCUHOfby_jG2HMDv_CfuDRYZenUILlwhsqllXo" alt="Joaco" width="75" height="75" style="border-radius: 50%;">
        </div>
        <div class="content ml-2" style="flex-grow: 1">
          <h3 style="margin-bottom: 0">CEO</h3>
          <p style="margin-bottom: 0">Joaquín Casanova</p>
          <a href="https://www.linkedin.com/in/joaquin-casanova-167347101/" target="_blank">
            <i class="fab fa-linkedin fa-lg"></i>
          </a>
          <a href="https://github.com/Joacocasanova" target="_blank">
            <i class="fab fa-github fa-lg"></i>
          </a>
        </div>      
      </div>

      <hr>

      <div class="integrante" style="display: flex;">
        <div class="img">
          <img src="https://media-exp1.licdn.com/dms/image/C4E03AQGdFmMtA_AFEQ/profile-displayphoto-shrink_800_800/0/1585506828516?e=1619049600&v=beta&t=78L4NCj3xoql2fWN-Y5CNbHYDCC5_deZo6GGDzz6pIE" alt="Ro" width="75" height="75" style="border-radius: 50%;">
        </div>
        <div class="content ml-2" style="flex-grow: 1">
          <h3 style="margin-bottom: 0">CFO</h3>
          <p style="margin-bottom: 0">Rocio Picaza</p>
          <a href="https://www.linkedin.com/in/rocio-belen-picaza-a5996833/" target="_blank">
            <i class="fab fa-linkedin fa-lg"></i>
          </a>
          <a href="https://github.com/ropicaza" target="_blank">
            <i class="fab fa-github fa-lg"></i>
          </a>
        </div>      
      </div>

      <hr>

      <div class="integrante" style="display: flex;">
        <div class="img">
          <img src="https://media-exp1.licdn.com/dms/image/C4E03AQFSPuxa6ibV-A/profile-displayphoto-shrink_800_800/0/1576292896774?e=1619049600&v=beta&t=nArAn2d7rZw1RPlt4S9Q6fuk5TiTfMfjDyjRyU_tGTs" alt="Tom" width="75" height="75" style="border-radius: 50%;">
        </div>
        <div class="content ml-2" style="flex-grow: 1">
          <h3 style="margin-bottom: 0">CTO</h3>
          <p style="margin-bottom: 0">Tomás Agnese</p>
          <a href="https://www.linkedin.com/in/tomasagnese/" target="_blank">
            <i class="fab fa-linkedin fa-lg"></i>
          </a>
          <a href="https://github.com/tomag1985" target="_blank">
            <i class="fab fa-github fa-lg"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <strong><h1 id="title" class="mt-3 fs-1 fw-bolder">Una nueva forma de organizar tus días</h1></strong>
      <p id="description" class="mt-3">Usá nuestro sistema de gestión de turnos en todos tus lugares favoritos y no esperes nunca más para entrar a un lugar.</p>
    </div>
    <div id="search-form">
      <%= form_with local: true, url: providers_path, method: :get do |f| %>
        <div class="row align-items-center m-0">
          <div class="mb-3 col-12 col-sm-12 col-md-6">
            <%=f.text_field :localidad, as: :string, required: true, placeholder:"¿Donde buscás?", id: "provider_address" %>
          </div>
          <div class="mb-3 col-12 col-sm-12 col-md-6">
            <%= f.select :categoria, [["Barberia", "Barberia"], ["Veterinaria", "Veterinaria"]], required: true, prompt: '¿Para qué es el turno?' %>
          </div>
          <div class="mb-3 col-12 col-md-6">
            <%= f.submit 'Buscar', class: "btn btn-lg btn-primary mt-2", style: "width:100%;border-radius:5px" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <hr class="my-3 py-3">
  <!--step 1 -->
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-6">
      <img class="m-3" src="https://res.cloudinary.com/dmtio0viw/image/upload/v1613101887/Turna/step1.png" alt="step1">
    </div>
    <div class="col-sm-12 col-md-6">
      <h3 id="title" class="m-3">Elegí la categoría que estás buscando</h3>
      <p id="description" class="m-3">Usá nuestro filtro para encontrar exactamente lo que estás buscando. ¡Tenemos todo tipo de servicios en Capital Federal!
      </p>
    </div>
  </div>
  <!--step 2 -->
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <img class="m-3" src="https://res.cloudinary.com/dmtio0viw/image/upload/v1613102136/Turna/step2.png" alt="step2">
    </div>
    <div class="col-sm-12 col-md-6">
      <h3 id="title" class="m-3">Elegí el lugar en donde queres recibir el servicio</h3>
      <p id="description" class="m-3">Selecciona el negocio que estas buscando según la ubicación elegida. Los lugares estan rankeados acorde a las reviews recibidas!
      </p>
    </div>
  </div>
  <!--step 3 -->
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <img class="w-100" src="https://res.cloudinary.com/dmtio0viw/image/upload/v1613102135/Turna/step3.png" alt="step3">
    </div>
    <div class="col-sm-12 col-md-6">
      <h3 id="title" class="m-3">Seleccioná tu servicio</h3>
      <p id="description" class="m-3">Una vez elegido el local, seleccioná el servicio en el que quieras reservar tu turno, y hacelo acorde a las disponibilidades del lugar/profesional elegido.
      </p>
    </div>
  </div>
</div>
<!--descargar Apple y iOS -->
<div class="container" style="background-color:#FE6929;height:400px;">
  <div class="container position text-center">
    <h3 id="title" style="color:white">¡No esperes un segundo más!</h3>
    <p id="description" style="color:white!important">Descargá nuestra app y reservá tu turno desde cualquier lado.</p>
    <div class="flex social-btns w-100">
      <a class="app-btn blu flex vert" href="https://www.apple.com/">
        <i class="fab fa-apple"></i>
        <p>Consíguelo en el <br/> <span class="big-txt">App Store</span></p>
      </a>

      <a class="app-btn blu flex vert" href="https://play.google.com/">
        <i class="fab fa-google-play"></i>
        <p>Disponible en <br/> <span class="big-txt">Google Play</span></p>
      </a>
    </div>
  </div>
</div>
<!--Nuestros negocios -->
<div class="container p-3">
  <h3 id="title">Nuestros negocios favoritos</h3>
  <div class="d-block d-md-none">
    <%= render 'shared/carousel' %>
  </div>
  <div class="d-none d-md-block">
    <%= render 'shared/cards_home' %>
  </div>
</div>

<!--Conocenos -->
<div class="container text-center" style="background-color:#FE6929;height:300px">
  <h3 id="title" style="color:white; padding-top:10px">¡No dudes en contactarnos!</h3>
  <div class="d-flex flex-column m-3 p-3">
    <%= link_to "¿Quienes somos?", about_path, class:"m-2", style:"color: white" %> <br>
    <%= link_to "Registrá tu negocio", new_provider_path, class: "m-2", style:"color: white" %>
  </div>
</div>

app/views/pages/introduction.html.erb
<div class="container-introduction vh-100 align-center">
  <div class="introduction-text w-40 d-flex flex-column">
    <img class="logo-introduction" src="https://res.cloudinary.com/divzp8hs4/image/upload/v1615419298/Turna/Logo_TurnaOK.png" alt="Logo Turna" width=100px>
    <p class="text-introduction my-2">Hacemos tu vida más fácil.</p>
    <div class="my-5">
      <%= link_to "Comenzar", home_path, class: "intro-btn btn btn-lg btn-primary mt-2" %>
    </div>
  </div>
</div>

app/views/pages/pending_providers.html.erb
<%= render 'shared/container' %>
<div class="container mb-5px">

  <strong><h1 id="title" class="pt-2">Nuestros proveedores</h1></strong>
  <div class="align-center">
    <ul class="nav nav-pills my-3" style="justify-content: evenly;" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button id="filters" class="btn btn-primary active m-1" id="pills-home-tab" data-toggle="pill" data-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Pendientes</button>
      </li>
      <li class="nav-item" role="presentation">
        <button id="filters" class="btn btn-primary m-1" id="pills-profile-tab" data-toggle="pill" data-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Activos</button>
      </li>
    </ul>
  </div>

    <div class="tab-content mt-5" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <div class="cards">
          <div class="row">
            <% @pending.each do |provider| %>
              <div class="col-12 col-md-4 mb-2">
                <%= link_to provider_path({id: provider.id, url: request.url}) do %>
                  <div class="card-product">
                    <%= cl_image_tag provider.photos.first.key, class: "card-img-index" %>
                    <div class="card-product-infos mt-2">
                      <h2><%= provider.name %></h2>
                      <p class="description" style="margin-top:0"><%= provider.services.first.title %></p>
                      <p class="description" style="margin-top:0">Precio promedio: <strong>$ <%= provider.avg_price %></strong></p>
                      <p class="description" style="margin:0">Creación: <%= provider.created_at.strftime('%d/%m/%Y') %></p>
                      <div class="d-flex align-items-center">
                        <%= link_to "Activar", provider_path(provider), method: :patch, class: "btn btn-primary mt-1 mb-2", style:"font-size:12px;border-radius:5px;height:30px" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

     <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="cards">
          <div class="row">
            <% @active.each do |provider| %>
              <div class="col-12 col-md-4 mb-2">
                <%= link_to provider_path({id: provider.id, url: request.url}) do %>
                  <div class="card-product">
                    <%= cl_image_tag provider.photos.first.key, class: "card-img-index" %>
                    <div class="card-product-infos mt-2">
                      <h2><%= provider.name %></h2>
                      <p class="description" style="margin-top:0"><%= provider.services.first.title %></p>
                      <p class="description" style="margin-top:0">Precio promedio: <strong>$ <%= provider.avg_price %></strong></p>
                      <p class="description" style="margin:0">Creación: <%= provider.created_at.strftime('%d/%m/%Y') %></p>
                      <div class="d-flex align-items-center">

                        <%= link_to "Desactivar", provider_path(provider), method: :patch, class: "btn btn-primary mt-1 mb-2", style:"font-size:12px;border-radius:5px;height:30px" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>